### ISSUE TITLE
Add support for `.strap/` directories

### ISSUE THREAD

**Issue by bobtiernay-okta** [ultimatedotfiles/strap#12]
Please add support for `.strap/` directories (containing `run.sh`, `playbook.yml`, etc) to prevent top-level directory sprawl and keep strap related resources together, similar to `.idea/`, `.github/`, `.git/`, etc.

**Comment by lhazlewood** [comment]
Fixed in https://github.com/ultimatedotfiles/strap/releases/tag/0.1.5 via https://github.com/ultimatedotfiles/strap/commit/a65bc90b1b8d81136ee5c62def95b305aa2ce679

**Comment by bobtiernay-okta** [comment]
Thanks @lhazlewood !
