### ISSUE TITLE
can not run strap

### ISSUE THREAD

**Issue by haoyuli-okta** [ultimatedotfiles/strap#27]
[error] Run 'strap lansible' as yourself, not root.
[error]     at main (/Users/haoyuli/.strap/releases/strap-0.3.6/cmd/lansible:138)
!!! FAILED
!!! Run '/Users/haoyuli/.strap/releases/strap-0.3.6/cmd/lansible --debug' for debugging output.
!!! If you're stuck: file an issue with debugging output at:
!!!   https://github.com/ultimatedotfiles/strap/issues/new

[haoyuli:~/okta/okta-core] haoyuli-OKTA-246593-old-reset-password-page 1 ± whoami
haoyuli

I don't think I am running as root, but encounter the following problem

**Comment by lhazlewood** [comment]
Hi @haoyuli-okta !  Strap has moved permanently to https://github.com/strapsh/strap
